### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by rjworks** [suman-kr/quoters#4]
Hi author, have you ever considered making this an NPM package? I like it a lot, but I’m writing an app using JavaScript

**Comment by rjworks** [comment]
Unless there’s an undocumented API or some sort.

**Comment by suman-kr** [comment]
Hey, thanks for the appreciation. I haven't created a NPM package for this library as of now. Maybe I'll create it and publish it soon  for the fellow javascript devs.

Meanwhile, you can use the API: http://py-quoters.herokuapp.com/
But. since it is hosted on heroku. It's response time is slow for first request.

**Comment by rjworks** [comment]
Oh ok… is there a way to collect quotes and save them to a json file or something?

**Comment by suman-kr** [comment]
Hey, I've published the npm package. [Here](https://www.npmjs.com/package/quoters)
I'll have to update the readme. 

```js
import Quote from "quoters"
console.log(new Quote("QUOTE").get())
```
Enjoy!!
